### ISSUE TITLE
Проблемы с pyttsx3

### ISSUE THREAD

**Issue by Futyn-Maker** [Oknolaz/vasisualy-windows#3]
Прежде всего, pyttsx3 отсутствует в `requirements.txt`, лучше, наверное, его туда добавить. Но это не проблема.
Установил этот модуль самостоятельно, но теперь при запуске получаю следующее.
```
Traceback (most recent call last):
  File "D:\Загрузки\vasisualy-windows-main\run.py", line 4, in <module>
    from vasisualy import main
  File "D:\Загрузки\vasisualy-windows-main\vasisualy\main.py", line 10, in <module>
    from .core import (speak, talk, recognise, defaults)
  File "D:\Загрузки\vasisualy-windows-main\vasisualy\core\speak.py", line 17, in <module>
    engine.setProperty("voice", voice.id)
AttributeError: 'str' object has no attribute 'id'
```
Проверьте, пожалуйста, правильность обращения к pyttsx3.

Спасибо!

**Comment by Oknolaz** [comment]
Возможно у вас не установлен синтезатор речи RHVoice. В скором времени это будет исправлено.
_Спасибо за бдительность_

**Comment by vajelski** [comment]
У меня та же проблема с настройкой RHvoice, но у Амина то же самое
